<Project Sdk="LibreWPF.Sdk/0.1.0-preview.27">
  <PropertyGroup>
    <TargetFramework>$(ProGpuWpfSdkSampleTargetFramework)</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>ICSharpCode.AvalonEdit</AssemblyName>
    <RootNamespace>ICSharpCode.AvalonEdit</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>ICSharpCode.AvalonEdit.snk</AssemblyOriginatorKeyFile>
    <DefineConstants>$(DefineConstants);LIBREWPF;NREFACTORY</DefineConstants>
    <NoWarn>$(NoWarn);1607;CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="obj/**" />
    <EmbeddedResource Remove="obj/**" />
    <None Remove="obj/**" />
    <Page Remove="obj/**" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Highlighting/Resources/*.xshd" />
    <EmbeddedResource Include="Highlighting/Resources/*.xsd" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\NRefactory\ICSharpCode.NRefactory\ICSharpCode.NRefactory.LibreWpf.csproj" />
  </ItemGroup>
</Project>
